name: Node.js Package

on:
    push:
        branches:
            - master
    workflow_dispatch:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: yarn
            - run: yarn lint
            - run: yarn test
            - run: yarn build

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: yarn
            - run: |
                  git config --local user.name 'github-actions[bot]'
                  git config --local user.email 'github-actions[bot]@users.noreply.github.com'
            - run: yarn publish:lerna
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    publish-github:
        needs: publish-npm
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: 'https://npm.pkg.github.com'
            - run: yarn
            - run: yarn publish:lerna:skip-git
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
